version: "3"

services:
  jeju-island-dialect-translation-program:
    build: .
    ports:
      - "2000:22"
    user: $DOCKER_USER:$DOCKER_GROUP
    volumes:
      - './:/home/Hosting/workspace:rw'
      - '~/.ssh:/home/Hosting/.ssh:ro'
